import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/sections/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white dark:bg-[#18181b]">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-[#18181b] text-black dark:text-gray-100`}
      >
        {/* LanguagePopup must be rendered in a Client Component, so move it to a client layout or page */}
        <div>
          <Header />
          <div className="min-h-screen">
            <div className="max-w-4xl mx-auto px-6 sm:px-8 lg:px-12 pt-24">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
